name: Docker Compose

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Docker Compose
      run: |
        docker compose up -d  # Run Docker Compose in detached mode
        # Wait for the Flask app to start
        until $(curl --output /dev/null --silent --head --fail http://localhost:5000); do
          printf '.'
          sleep 1
        done
