name: setup-compose
on: [push, pull_request]

jobs:
    setup-compose:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.10" 
        - name: Set up MongoDB Shell (mongosh)
          run: |
            curl -sS https://www.mongodb.com/try/download/shell | bash
            export PATH="$PATH:/path/to/mongosh/bin" # Replace "/path/to/mongosh/bin" with the actual path to the mongosh binary directory
            mongosh --version
        - name: compose file
          run: |
            docker compose up -d
        - name: Ensure database is running
          run: |
            if ! mongosh --quiet --eval 'db.getMongo().getDBNames().indexOf("admin")'; then
              echo "Error: MongoDB connection failed."
              exit 1
            fi
        - name: Ensure web app is running
          run: |
            curl -s http://localhost:5000 || exit 1
  